#!/usr/bin/env ruby

require 'erb'
require 'optparse'
require 'srvrouter'

include SRVRouter

template_file = File.join(File.dirname(File.expand_path(__FILE__)), "../templates/haproxy.cfg.erb")

options = {
  :service => 'service',
  :port => 80,
  :name => 'service.marathon.mesos',
}

OptionParser.new do |opts|
  opts.banner = "Usage: srvrouter [options]"

  opts.on("-n", "--name NAME", "DNS name to lookup") do |name|
    options[:name] = name
  end

  opts.on("-s", "--service SERVICE", "Service to monitor") do |service|
    options[:service] = service
  end

  opts.on("-p", "--port PORT", Integer, "Port to listen on") do |port|
    options[:port] = port
  end

  opts.on("-o", "--output FILE", "File to write to") do |out_file|
    options[:output] = out_file
  end
end.parse!

answers = SRVRouter::lookup_srv(options[:name])
cfg = SRVRouter::HAProxyConfig.new(options[:service], options[:port], answers)
renderer = ERB.new(File.read(template_file))
output = renderer.result(cfg.get_binding)

if options[:output] != nil
  File.open(options[:output], "w") do |file|
    file.write(output)
  end
else
  puts output
end
